CREATE TABLE users(
    id_user BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uuid_user uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE urls(
    id_url BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    uuid_url uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    id_user BIGINT NOT NULL,
    target_url VARCHAR(2048) NOT NULL,
    short_code VARCHAR(16) NOT NULL UNIQUE,
    status VARCHAR(128) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (id_user) REFERENCES users(id_user) ON DELETE CASCADE
);

ALTER TABLE urls
    ADD CHECK (status IN ('ACTIVE', 'INACTIVE'));